#################################################################################################
#                                                                                               #
# Copyright © 2019 Acoustic, L.P. All rights reserved.                                          #
#                                                                                               #
# NOTICE: This file contains material that is confidential and proprietary to                   #
# Acoustic, L.P. and/or other developers. No license is granted under any intellectual or       #
# industrial property rights of Acoustic, L.P. except as may be provided in an agreement with   #
# Acoustic, L.P. Any unauthorized copying or distribution of content from this file is          #
# prohibited.                                                                                   #
#                                                                                               #
#################################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: precs-vtb-RAND_TIME
spec:
  ttlSecondsAfterFinished: 6048000
  template:
    spec:
      containers:
      - name: precs-python
        image: IMAGE_NAME
        command: ["python", "viewtobuy_main.py", "PYTHON_PARAMS"]
        resources:
            limits:
              #cpu: 50000m
              #memory: 60000Mi
            requests:
              cpu: 5000m
              memory: 19000Mi
      tolerations:
      - key: "ml-python"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: node-config-type
                operator: In
                values:
                - ml-python
      imagePullSecrets:
        - name: alston.artifactorypass
      restartPolicy: Never
  backoffLimit: 0
